export const projects = [  
   {  
      "name":"Zoho",
      "tasks":[  
         {  
            "id":"JCI-8798",
            "isCompleted":true
         },
         {  
            "id":"JCI-8791",
            "isCompleted":true
         },
         {  
            "id":"JCI-8792",
            "isCompleted":true
         },
         {  
            "id":"JCI-8793",
            "isCompleted":true
         },
         {  
            "id":"JCI-8794",
            "isCompleted":false
         },
         {  
            "id":"JCI-8795",
            "isCompleted":false
         },
         {  
            "id":"JCI-8796",
            "isCompleted":false
         }
      ]
   },
   {  
      "name":"Salesforce V2",
      "tasks":[  
         {  
            "id":"JCI-8798",
            "isCompleted":true
         },
         {  
            "id":"JCI-8791",
            "isCompleted":false
         },
         {  
            "id":"JCI-8792",
            "isCompleted":false
         },
         {  
            "id":"JCI-8793",
            "isCompleted":false
         },
         {  
            "id":"JCI-8794",
            "isCompleted":false
         },
         {  
            "id":"JCI-8795",
            "isCompleted":false
         },
         {  
            "id":"JCI-8796",
            "isCompleted":false
         }
      ]
   }
]